/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Languages */
        get: operations["list_languages_api_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Glossary Entries */
        get: operations["list_glossary_entries_api_glossary_get"];
        put?: never;
        /** Create Glossary Entry */
        post: operations["create_glossary_entry_api_glossary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Glossary Entry */
        get: operations["get_glossary_entry_api_glossary__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete Glossary Entry */
        delete: operations["delete_glossary_entry_api_glossary__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Glossary Entry */
        patch: operations["update_glossary_entry_api_glossary__entry_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DuplicateTermsDetail */
        DuplicateTermsDetail: {
            /** Message */
            message: string;
            /** Conflicts */
            conflicts: components["schemas"]["TermConflict"][];
        };
        /** DuplicateTermsResponse */
        DuplicateTermsResponse: {
            detail: components["schemas"]["DuplicateTermsDetail"];
        };
        /**
         * GlossaryCategory
         * @enum {string}
         */
        GlossaryCategory: "kitchen_term" | "product_name" | "general";
        /** GlossaryEntryCreate */
        GlossaryEntryCreate: {
            /** @default general */
            category: components["schemas"]["GlossaryCategory"];
            /**
             * Do Not Translate
             * @default false
             */
            do_not_translate: boolean;
            /**
             * Case Sensitive
             * @default false
             */
            case_sensitive: boolean;
            /** Description */
            description?: string | null;
            /** Terms */
            terms: components["schemas"]["TermIn"][];
        };
        /** GlossaryEntryOut */
        GlossaryEntryOut: {
            /** Id */
            id: number;
            category: components["schemas"]["GlossaryCategory"];
            /** Do Not Translate */
            do_not_translate: boolean;
            /** Case Sensitive */
            case_sensitive: boolean;
            /** Description */
            description: string | null;
            /** Terms */
            terms: components["schemas"]["TermOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * GlossaryEntryUpdate
         * @description Partial update. `terms`, when given, replaces the entry's full set of terms.
         */
        GlossaryEntryUpdate: {
            category?: components["schemas"]["GlossaryCategory"] | null;
            /** Do Not Translate */
            do_not_translate?: boolean | null;
            /** Case Sensitive */
            case_sensitive?: boolean | null;
            /** Description */
            description?: string | null;
            /** Terms */
            terms?: components["schemas"]["TermIn"][] | null;
        };
        /** GlossaryPage */
        GlossaryPage: {
            /** Items */
            items: components["schemas"]["GlossaryEntryOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
        };
        /** LanguageOut */
        LanguageOut: {
            /**
             * Code
             * @enum {string}
             */
            code: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
            /** Name */
            name: string;
        };
        /** TermConflict */
        TermConflict: {
            /**
             * Language
             * @enum {string}
             */
            language: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
            /** Text */
            text: string;
            /** Entry Id */
            entry_id: number;
        };
        /** TermIn */
        TermIn: {
            /**
             * Language
             * @enum {string}
             */
            language: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
            /** Text */
            text: string;
        };
        /** TermOut */
        TermOut: {
            /**
             * Language
             * @enum {string}
             */
            language: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_languages_api_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"][];
                };
            };
        };
    };
    list_glossary_entries_api_glossary_get: {
        parameters: {
            query?: {
                /** @description Search terms in all languages */
                q?: string | null;
                category?: components["schemas"]["GlossaryCategory"] | null;
                do_not_translate?: boolean | null;
                /** @description Only entries without a term in this language */
                missing?: ("de" | "en" | "fr" | "nl" | "da" | "nb" | "es") | null;
                sort?: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es" | "created_at" | "updated_at";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_glossary_entry_api_glossary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryEntryOut"];
                };
            };
            /** @description A term already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateTermsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_glossary_entry_api_glossary__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryEntryOut"];
                };
            };
            /** @description Glossary entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_glossary_entry_api_glossary__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Glossary entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_glossary_entry_api_glossary__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryEntryOut"];
                };
            };
            /** @description Glossary entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A term already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateTermsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
