/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Languages */
        get: operations["list_languages_api_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Glossary Entries */
        get: operations["list_glossary_entries_api_glossary_get"];
        put?: never;
        /** Create Glossary Entry */
        post: operations["create_glossary_entry_api_glossary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Glossary Entry */
        get: operations["get_glossary_entry_api_glossary__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete Glossary Entry */
        delete: operations["delete_glossary_entry_api_glossary__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Glossary Entry */
        patch: operations["update_glossary_entry_api_glossary__entry_id__patch"];
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Project
         * @description Upload a PDF, parse its contents, detect languages, and create a new project.
         *
         *     Args:
         *         file: The uploaded PDF file payload.
         *         db_session: The active asynchronous database session.
         *
         *     Returns:
         *         ProjectResponse containing the new project's metadata, parsed pages, and segments.
         *
         *     Raises:
         *         HTTPException: 400 for missing filename or bad PDF, 500 for unhandled parsing errors.
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Get a project and all its parsed contents.
         *
         *     Args:
         *         project_id: The UUID of the project to retrieve.
         *         db_session: The active asynchronous database session.
         *
         *     Returns:
         *         ProjectResponse representing the requested project.
         */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Project
         * @description Update a project, typically to confirm or change its source language.
         *
         *     Changing the source language recalculates the 'is_translatable' flag
         *     for every segment in the project.
         *
         *     Args:
         *         project_id: The UUID of the project to update.
         *         payload: ProjectUpdateRequest containing the new source language.
         *         db_session: The active asynchronous database session.
         *
         *     Returns:
         *         ProjectResponse representing the updated project.
         */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Segment
         * @description Manually edit the translation for a single document segment.
         *
         *     Args:
         *         project_id: The UUID of the project.
         *         segment_id: The UUID of the segment to edit.
         *         payload: SegmentEditRequest containing target language and new text.
         *         db_session: The active asynchronous database session.
         *         current_user: The authenticated user.
         *
         *     Returns:
         *         The updated DocumentSegment object.
         *
         *     Raises:
         *         HTTPException: 404 if the project or segment is not found.
         */
        patch: operations["edit_segment_api_projects__project_id__segments__segment_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/segments/{segment_id}/retranslate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retranslate Segment
         * @description Re-translate a single document segment synchronously.
         *
         *     Args:
         *         project_id: The UUID of the project.
         *         segment_id: The UUID of the segment to re-translate.
         *         payload: TranslateRequest containing the target language code.
         *         db_session: The active asynchronous database session.
         *
         *     Returns:
         *         The updated DocumentSegment object.
         *
         *     Raises:
         *         HTTPException: 404 if the project or segment is not found.
         *         HTTPException: 400 if the document has no source language or segment is not translatable.
         */
        post: operations["retranslate_segment_api_projects__project_id__segments__segment_id__retranslate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate Project
         * @description Trigger the translation of a project.
         *
         *     This endpoint returns immediately (202 Accepted) while the translation
         *     orchestrator processes the document segments in the background.
         *
         *     Args:
         *         project_id: The UUID of the project to translate.
         *         payload: TranslateRequest containing the target language code.
         *         background_tasks: FastAPI BackgroundTasks runner.
         *         db_session: The active asynchronous database session.
         *
         *     Returns:
         *         A dictionary containing a success message indicating background processing started.
         *
         *     Raises:
         *         HTTPException: 400 if the project has no documents or is missing a source language.
         */
        post: operations["translate_project_api_projects__project_id__translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/segments/{segment_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Segment Comment
         * @description Add a new comment to a specific segment.
         */
        post: operations["add_segment_comment_api_projects__project_id__segments__segment_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/segments/{segment_id}/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Segment Comment
         * @description Delete a specific comment.
         */
        delete: operations["delete_segment_comment_api_projects__project_id__segments__segment_id__comments__comment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login For Access Token
         * @description Authenticate a user and return a JWT access token.
         *
         *     Args:
         *         form_data: OAuth2 form data containing the username (email) and password.
         *         db_session: The active asynchronous database session.
         *
         *     Returns:
         *         A Token object containing the signed JWT access token.
         *
         *     Raises:
         *         HTTPException: 401 if the user is not found or the password does not match.
         */
        post: operations["login_for_access_token_api_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Users Me
         * @description Get the currently authenticated user's profile.
         *
         *     Args:
         *         current_user: The authenticated User object injected by the dependency.
         *
         *     Returns:
         *         The current User object.
         */
        get: operations["read_users_me_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Users
         * @description List all users in the system. Only accessible by administrators.
         *
         *     Args:
         *         db_session: The active asynchronous database session.
         *         current_user: The authenticated admin User object injected by the dependency.
         *
         *     Returns:
         *         A list of User objects.
         */
        get: operations["read_users_api_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create a new user. Only accessible by administrators.
         *
         *     Args:
         *         user_in: The UserCreate schema containing the new user's details.
         *         db_session: The active asynchronous database session.
         *         current_user: The authenticated admin User object injected by the dependency.
         *
         *     Returns:
         *         The newly created User object.
         *
         *     Raises:
         *         HTTPException: 400 if the email is already registered.
         */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_project_api_projects_post */
        Body_create_project_api_projects_post: {
            /** File */
            file: string;
        };
        /** Body_login_for_access_token_api_auth_token_post */
        Body_login_for_access_token_api_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** DocumentPageSchema */
        DocumentPageSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Warnings */
            warnings: string[];
        };
        /** DocumentSchema */
        DocumentSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Source Language */
            source_language: ("de" | "en" | "fr" | "nl" | "da" | "nb" | "es") | null;
            /** Pages */
            pages: components["schemas"]["DocumentPageSchema"][];
            /** Segments */
            segments: components["schemas"]["DocumentSegmentSchema"][];
        };
        /** DocumentSegmentSchema */
        DocumentSegmentSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Page Number */
            page_number: number;
            /** Order Index */
            order_index: number;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Bounding Box */
            bounding_box: number[];
            /** Detected Language */
            detected_language: string | null;
            /** Is Translatable */
            is_translatable: boolean | null;
            /** Translations */
            translations: {
                [key: string]: string;
            };
            /** Annotations */
            annotations?: {
                [key: string]: {
                    [key: string]: unknown;
                }[];
            };
            /** Issues */
            issues?: {
                [key: string]: {
                    [key: string]: unknown;
                }[];
            };
            /** Comments */
            comments?: components["schemas"]["SegmentCommentResponse"][];
        };
        /** DuplicateTermsDetail */
        DuplicateTermsDetail: {
            /** Message */
            message: string;
            /** Conflicts */
            conflicts: components["schemas"]["TermConflict"][];
        };
        /** DuplicateTermsResponse */
        DuplicateTermsResponse: {
            detail: components["schemas"]["DuplicateTermsDetail"];
        };
        /**
         * GlossaryCategory
         * @enum {string}
         */
        GlossaryCategory: "kitchen_term" | "product_name" | "general";
        /** GlossaryEntryCreate */
        GlossaryEntryCreate: {
            /** @default general */
            category: components["schemas"]["GlossaryCategory"];
            /**
             * Do Not Translate
             * @default false
             */
            do_not_translate: boolean;
            /**
             * Case Sensitive
             * @default false
             */
            case_sensitive: boolean;
            /** Description */
            description?: string | null;
            /** Terms */
            terms: components["schemas"]["TermIn"][];
        };
        /** GlossaryEntryOut */
        GlossaryEntryOut: {
            /** Id */
            id: number;
            category: components["schemas"]["GlossaryCategory"];
            /** Do Not Translate */
            do_not_translate: boolean;
            /** Case Sensitive */
            case_sensitive: boolean;
            /** Description */
            description: string | null;
            /** Terms */
            terms: components["schemas"]["TermOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * GlossaryEntryUpdate
         * @description Partial update. `terms`, when given, replaces the entry's full set of terms.
         */
        GlossaryEntryUpdate: {
            category?: components["schemas"]["GlossaryCategory"] | null;
            /** Do Not Translate */
            do_not_translate?: boolean | null;
            /** Case Sensitive */
            case_sensitive?: boolean | null;
            /** Description */
            description?: string | null;
            /** Terms */
            terms?: components["schemas"]["TermIn"][] | null;
        };
        /** GlossaryPage */
        GlossaryPage: {
            /** Items */
            items: components["schemas"]["GlossaryEntryOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
        };
        /** LanguageOut */
        LanguageOut: {
            /**
             * Code
             * @enum {string}
             */
            code: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
            /** Name */
            name: string;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            status: components["schemas"]["ProjectStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Documents */
            documents: components["schemas"]["DocumentSchema"][];
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "new" | "translating" | "review" | "done";
        /** ProjectUpdateRequest */
        ProjectUpdateRequest: {
            /**
             * Source Language
             * @enum {string}
             */
            source_language: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "reviewer" | "translator";
        /** SegmentCommentAuthor */
        SegmentCommentAuthor: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
        };
        /** SegmentCommentCreate */
        SegmentCommentCreate: {
            /**
             * Text
             * @description Comment text
             */
            text: string;
        };
        /** SegmentCommentResponse */
        SegmentCommentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Segment Id
             * Format: uuid
             */
            segment_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            user?: components["schemas"]["SegmentCommentAuthor"] | null;
        };
        /** SegmentEditRequest */
        SegmentEditRequest: {
            /**
             * Target Language
             * @enum {string}
             */
            target_language: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
            /** New Text */
            new_text: string;
        };
        /** TermConflict */
        TermConflict: {
            /**
             * Language
             * @enum {string}
             */
            language: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
            /** Text */
            text: string;
            /** Entry Id */
            entry_id: number;
        };
        /** TermIn */
        TermIn: {
            /**
             * Language
             * @enum {string}
             */
            language: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
            /** Text */
            text: string;
        };
        /** TermOut */
        TermOut: {
            /**
             * Language
             * @enum {string}
             */
            language: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
            /** Text */
            text: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** TranslateRequest */
        TranslateRequest: {
            /**
             * Target Language
             * @enum {string}
             */
            target_language: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es";
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** @default translator */
            role: components["schemas"]["Role"];
            /** Password */
            password: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** @default translator */
            role: components["schemas"]["Role"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_languages_api_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"][];
                };
            };
        };
    };
    list_glossary_entries_api_glossary_get: {
        parameters: {
            query?: {
                /** @description Search terms in all languages */
                q?: string | null;
                category?: components["schemas"]["GlossaryCategory"] | null;
                do_not_translate?: boolean | null;
                case_sensitive?: boolean | null;
                /** @description Only entries without a term in this language */
                missing?: ("de" | "en" | "fr" | "nl" | "da" | "nb" | "es") | null;
                sort?: "de" | "en" | "fr" | "nl" | "da" | "nb" | "es" | "created_at" | "updated_at";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_glossary_entry_api_glossary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryEntryOut"];
                };
            };
            /** @description A term already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateTermsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_glossary_entry_api_glossary__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryEntryOut"];
                };
            };
            /** @description Glossary entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_glossary_entry_api_glossary__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Glossary entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_glossary_entry_api_glossary__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryEntryOut"];
                };
            };
            /** @description Glossary entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A term already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateTermsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_project_api_projects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_segment_api_projects__project_id__segments__segment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSegmentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retranslate_segment_api_projects__project_id__segments__segment_id__retranslate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSegmentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_project_api_projects__project_id__translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_segment_comment_api_projects__project_id__segments__segment_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentCommentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentCommentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_segment_comment_api_projects__project_id__segments__segment_id__comments__comment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                segment_id: string;
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_for_access_token_api_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_api_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_users_me_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    read_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
