"""add annotations to document segment

Revision ID: 0b4a853c6c7b
Revises: 2b4d7aaa8717
Create Date: 2026-10-07 17:27:37.802109

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b4a853c6c7b"
down_revision: str | Sequence[str] | None = "2b4d7aaa8717"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_segments",
        sa.Column("annotations", sa.JSON(), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_segments", "annotations")
    # ### end Alembic commands ###
