"""Add issues column to document_segment

Revision ID: db3ed1335b80
Revises: 0b4a853c6c7b
Create Date: 2026-10-09 18:38:24.090521

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db3ed1335b80"
down_revision: str | Sequence[str] | None = "0b4a853c6c7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_segments", sa.Column("issues", sa.JSON(), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_segments", "issues")
    # ### end Alembic commands ###
