"""Add translations JSON column to DocumentSegment

Revision ID: 2b4d7aaa8717
Revises: f6c2659a40fb
Create Date: 2026-10-06 23:56:39.125928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4d7aaa8717'
down_revision: Union[str, Sequence[str], None] = 'f6c2659a40fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_segments', sa.Column('translations', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_segments', 'translations')
    # ### end Alembic commands ###
