"""Add SegmentComment model

Revision ID: e9ba7dc9610c
Revises: c393c84d6358
Create Date: 2026-10-10 18:37:49.118304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ba7dc9610c'
down_revision: Union[str, Sequence[str], None] = 'c393c84d6358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=10000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['document_segments.id'], name=op.f('fk_segment_comments_segment_id_document_segments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_segment_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segment_comments'))
    )
    op.create_index(op.f('ix_segment_comments_segment_id'), 'segment_comments', ['segment_id'], unique=False)
    op.create_index(op.f('ix_segment_comments_user_id'), 'segment_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_comments_user_id'), table_name='segment_comments')
    op.drop_index(op.f('ix_segment_comments_segment_id'), table_name='segment_comments')
    op.drop_table('segment_comments')
    # ### end Alembic commands ###
